name: Rave-Up
title: Rave-Up Records
description: "Obscure nuggets from the golden age of ROCK'n ROLL"
logo: /assets/images/logo2019.png
baseurl:
permalink: /:categories/:title
excerpt_separator: "\n\n"
relative_permalinks: false
exclude: [ php ]
url: https://www.raveuprecords.com
timezone: Europe/Rome
plugins:
  - jekyll-sitemap
  - jekyll-coffeescript
sass:
  sass_dir: _sass
  style: compressed
script:
  - js/jquery-1.10.1.min.js
  - js/jquery.ui.totop.js
  - js/easing.js
  - js/main.js
  - js/md5.min.js
  - js/buy.js
collections:
  blog:
    output: true