markdown: rdiscount
baseurl:
permalink: /:categories/:title
excerpt_separator: "\n\n"
relative_permalinks: false
exclude: [ php ]

url:

gems:
  - jekyll-feed
  - jekyll-sitemap

name: Rave-Up
title: Rave-Up records
description: Obscure nuggets from the golden age of ROCK n ROLL

# OUTDATE General for posts tagged `new`
# override in post with `outdate: ...`
outdate: OUT NOW!

sass:
  sass_dir: _sass
  style: :compressed

script:
  - js/jquery-1.10.1.min.js
  - js/jquery.ui.totop.js
  - js/easing.js
  - js/main.js
  - js/md5.min.js
