# markdown: rdiscount
# nope, we use kramdown (https://help.github.com/articles/updating-your-markdown-processor-to-kramdown)
baseurl:
permalink: /:categories/:title
excerpt_separator: "\n\n"
relative_permalinks: false
exclude: [ php ]

url:

gems:
  - jekyll-feed
  - jekyll-sitemap

name: Rave-Up
title: Rave-Up records
description: Obscure nuggets from the golden age of ROCK n ROLL

# OUTDATE General for posts tagged `new`
# override in post with `outdate: ...`
outdate: OUT MAY 15TH 2016!

# BLOG and announcements
collections:
  blog:
    output: false

# Announcements to show
announcements: 1

sass:
  sass_dir: _sass
  style: :compressed

script:
  - js/jquery-1.10.1.min.js
  - js/jquery.ui.totop.js
  - js/easing.js
  - js/main.js
  - js/md5.min.js
